name: Docker Compose CI + Push to GHCR

on:
  push:
    branches:
      - Lab-7
  pull_request:
    branches:
      - Lab-7

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker images
        run: docker compose build

      - name: Tag Docker images with branch name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Tagging images with branch name: $BRANCH_NAME"

          # Etiqueta la imagen java-app
          docker tag java_app ghcr.io/your-username/your-repo/java-app:$BRANCH_NAME

          # Etiqueta la imagen java-db
          docker tag java_db ghcr.io/your-username/your-repo/java-db:$BRANCH_NAME

      - name: Push Docker images to GHCR
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Pushing images to GHCR with branch name: $BRANCH_NAME"

          # Empuja la imagen java-app a GHCR
          docker push ghcr.io/your-username/your-repo/java-app:$BRANCH_NAME

          # Empuja la imagen java-db a GHCR
          docker push ghcr.io/your-username/your-repo/java-db:$BRANCH_NAME

      - name: Stop containers
        run: docker-compose down